apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-first-rs
spec:
  template:
    metadata:
      #name: my-first-rs-pod
      labels:
        type: frontend
    spec:
      containers:
        - name: my-first-rs-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend