apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-for-service
  labels:
    type: Labels-For-Node-Port-Service
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 80
      port: 80 
      nodePort: 30020 ### Port Range - 30000-32767
      protocol: TCP
  selector:
    app: nginx